{
 "title": "test1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Number of UE",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics_summary\")\n  |> filter(fn: (r) => r._field == \"UE_Count\")\n  |> filter(fn: (r) => r.e2_node == \"gnbd_001_001_00019b_0\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "% Used PRB ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\" and r._field == \"PRB_TotUl\")\n  |> last()\n  |> map(fn: (r) => ({ \n      r with \n      _field: \"UE_\" + string(v: r.ue_id)\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "PRB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"prb_metrics\")\n  |> filter(fn: (r) => r._field == \"PRB_TotalDL\")\n  |> filter(fn: (r) => r.e2_node == \"gnbd_001_001_00019b_0\")\n  |> last()\n"
    },
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"prb_metrics\")\n  |> filter(fn: (r) => r._field == \"PRB_TotalUL\")\n  |> filter(fn: (r) => r.e2_node == \"gnbd_001_001_00019b_0\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Thrput_DL (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\" and r._field == \"DRB_UEThpDl\")\n  |> map(fn: (r) => ({\n      r with\n      _field: \"UE_\" + string(v: r.ue_id)\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n"
    }
   ]
  },
  {
   "title": "Thrput_UL (kbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\" and r._field == \"DRB_UEThpUl\")\n  |> map(fn: (r) => ({\n      r with\n      _field: \"UE_\" + string(v: r.ue_id)\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n"
    }
   ]
  },
  {
   "title": "RlcSduDelayDl (ms )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\" and r._field == \"RlcSduDelayDl\")\n  |> map(fn: (r) => ({\n      r with\n      _field: \"UE_\" + string(v: r.ue_id)\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n"
    }
   ]
  },
  {
   "title": "RlcDelayUl (ms )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"srsran\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\" and r._field == \"RlcDelayUl\")\n  |> map(fn: (r) => ({\n      r with\n      _field: \"UE_\" + string(v: r.ue_id)\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n"
    }
   ]
  },
  {
   "title": "RlcSduTransmittedVolumeDL (kbit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\" and r._field == \"RlcSduTransmittedVolumeDL\")\n  |> map(fn: (r) => ({\n      r with\n      _field: \"UE_\" + string(v: r.ue_id)\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "RlcSduTransmittedVolumeUL (kbit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"ue_metrics\" and r._field == \"RlcSduTransmittedVolumeUL\")\n  |> map(fn: (r) => ({\n      r with\n      _field: \"UE_\" + string(v: r.ue_id)\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "CQI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"srsran\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"prb_metrics\")\n  |> filter(fn: (r) => r._field == \"CQI\")\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}